Script started on Fri 11 Mar 2016 03:23:33 PM CST
]0;yuki_n@yuki-n-pc: ~[01;31myuki_n@yuki-n-pc[00m:[01;34m~[00m$ g+{[K+ -o hw1.exe prgr_hw1.cpp 
]0;yuki_n@yuki-n-pc: ~[01;31myuki_n@yuki-n-pc[00m:[01;34m~[00m$ ./hw1.exe 
Please in put a integer n : 22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;yuki_n@yuki-n-pc: ~[01;31myuki_n@yuki-n-pc[00m:[01;34m~[00m$ exit

Script done on Fri 11 Mar 2016 03:24:11 PM CST
